# Generated by Django 5.2.4 on 2025-07-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayerApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_category',
        ),
        migrations.DeleteModel(
            name='GameCategory',
        ),
    ]
