# Generated by Django 5.2.4 on 2025-07-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayerApp', '0005_themecategory_bets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bets',
        ),
        migrations.DeleteModel(
            name='ThemeCategory',
        ),
    ]
