# Generated by Django 5.2.4 on 2025-07-24 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayerApp', '0006_delete_bets_delete_themecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('themeCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_categories', to='multiplayerApp.themecategory')),
            ],
        ),
    ]
