# Generated by Django 5.2.4 on 2025-07-24 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayerApp', '0007_themecategory_bets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betcategory',
            name='game',
        ),
        migrations.RemoveField(
            model_name='bets',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bets',
            name='themeCategory',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
