# Generated by Django 5.2.4 on 2025-07-24 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayerApp', '0008_remove_betcategory_game_remove_bets_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bets',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bets',
            name='themeCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_categories', to='multiplayerApp.themecategory'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('game_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_category', to='multiplayerApp.gamecategory')),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_types', to='multiplayerApp.gametypes')),
            ],
        ),
        migrations.AddField(
            model_name='betcategory',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bet_categories', to='multiplayerApp.game'),
        ),
    ]
