# Generated by Django 5.2.4 on 2025-07-25 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayerApp', '0009_bets_description_bets_themecategory_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaughtyCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('theme_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_category_cards', to='multiplayerApp.themecategory')),
            ],
        ),
        migrations.CreateModel(
            name='TruthNDare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('theme_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='theme_category_dare', to='multiplayerApp.themecategory')),
            ],
        ),
    ]
